export default {
  //root main
  AUTH_NAVIGATION: 'AUTH_NAVIGATION',
  BOTTOM_NAVIGATION: 'BOTTOM_NAVIGATION',
  COMMON_NAVIGATION: 'COMMON_NAVIGATION',

  //bottom container
  HOME_SCREEN: 'HOME_SCREEN',
  SHORT_SCREEN: 'SHORT_SCREEN',
  SUBSCRIPTION: 'SUBSCRIPTION',
  LIBRARY: 'LIBRARY',

  ACCOUNT_SCREEN: 'ACCOUNT_SCREEN',
  WALLET_SCREEN: 'WALLET_SCREEN',

  //auth container
  SIGN_IN_SCREEN: 'SIGN_IN_SCREEN',
  SIGN_UP_SCREEN: 'SIGN_UP_SCREEN',

  //common container
  SAVING_SCREEN: 'SAVING_SCREEN',
  NFT_DETAIL_SCREEN: 'NFT_DETAIL_SCREEN',
  USER_INFO_SCREEN: 'USER_INFO_SCREEN',
};
